---
- hosts: all
  remote_user: vagrant
  sudo: yes
  sudo_user: root
  vars:
    username: vagrant
  tasks:
    - include: ../modules/ubuntu/playbooks/fixes.yml
    - include: ../modules/timezone/playbooks/sydney.yml
    - include: ../modules/utils/playbooks/base.yml
    - include: ../modules/vcs/playbooks/git.yml
    - include: ../modules/nodejs/playbooks/base.yml

