---
- name: Has the swapfile already been created?
  command: /bin/grep --quiet 'swapfile' /etc/fstab
  register: swapfile_exists
  ignore_errors: True
- name: Create the swapfile
  shell: /bin/bash /vagrant-share/conf/oraclexe/create-swap-file.sh
  when: swapfile_exists|failed

