---
- name: Install wkhtmltopdf prerequisites
  apt: pkg={{ item }}
  with_items:
   - fontconfig
   - libjpeg-turbo8
   - xfonts-75dpi
- name: Download wkhtmltopdf DEB
  get_url: url=http://aarnet.dl.sourceforge.net/project/wkhtmltopdf/0.12.2.1/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
           dest=/vagrant-share/apps/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb
           sha256sum=1cf47ab83a3352e7df95f2973061e8c90daabb1333f00e2385cb8b2b0ff22a90
- name: Install wkhtmltopdf using dpkg
  apt: deb=/vagrant-share/apps/wkhtmltox-0.12.2.1_linux-trusty-amd64.deb

