---
- hosts: all
  remote_user: vagrant
  sudo: yes
  sudo_user: root
  vars:
    username: vagrant
  tasks:
    - include: ../modules/ubuntu/playbooks/fixes.yml
    - include: ../modules/timezone/playbooks/sydney.yml
    - include: ../modules/utils/playbooks/base.yml
    - include: ../modules/xwindows/playbooks/hideerrors.yml
    - include: ../modules/fonts/playbooks/microsoft.yml
    - include: ../modules/webbrowser/playbooks/chrome.yml
    - include: ../modules/apps/playbooks/evince.yml
    - include: ../modules/java/playbooks/oraclejdk8.yml
