---
- include: ./boost-source.yml
#- include: ./boost.yml
# - name: Set up support for libraries installed in /usr/local/lib
#   shell: /bin/echo '/usr/local/lib' > /etc/ld.so.conf.d/boost.conf && /sbin/ldconfig
#          creates=/etc/ld.so.conf.d/boost.conf
# - name: Download Mapnik source
#   git: repo=https://github.com/mapnik/mapnik.git
#        dest=/tmp/mapnik
#        recursive=yes
#        version=2.3.x
#        force=yes
#        accept_hostkey=yes
# - copy: src=../../../share/conf/mapnik/config.py
#         dest=/tmp/mapnik/config.py
#         force=yes
#         mode=0664 owner=root group=root
# - name: Configure Mapnik build
#   shell: /tmp/mapnik/configure > /tmp/mapnik-configure.log
#          chdir=/tmp/mapnik
#          creates=/tmp/mapnik/config.log
# - name: Build Mapnik
#   shell: /usr/bin/make > /tmp/mapnik-build.log
#          chdir=/tmp/mapnik
#          creates=/tmp/mapnik/src/libmapnik.so
# - name: Install Mapnik (requires sudo)
#   shell: /usr/bin/make install > /tmp/mapnik-install.log
#          chdir=/tmp/mapnik
#          creates=/usr/local/lib/libmapnik.so.2.3


